name: Automatically deploy workflow to myth
on:
  push:

permissions:
  contents: read
  actions: write

jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build
    - run: cd build && tar -czvf ../deploy.tar.gz . && cd ..
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: deploy.tar.gz
        path: deploy.tar.gz
        retention-days: 1
    - env:
        AUTH_CODE: ${{ secrets.AUTH_CODE }}
      run: |-
        curl -LX POST -d '${{ github.token }}' \
          -H "Content-Type: text/plain" \
          -H "X-Auth-Code: $AUTH_CODE" \
          -H "X-Finish: true" \
          https://cs45.stanford.edu/cgi-bin/deploy.sh;